$(document).ready(function(){
 $('#productos').on('click',function(){
    $('#pnivel2').slideToggle('slow');
    $('#snivel2').hide();
 });
 $('#servicios').on('click',function(){
    $('#snivel2').slideToggle('slow');
    $('#pnivel2').hide();
 });
 $('#subproductos1').on('click',function(){
    $('#subnivel1').toggle('slow');
    $('#subnivel2').hide();
    $('#subnivel3').hide();
    $('#subnivel4').hide();
    $('#subnivel5').hide();
    $('#subnivel6').hide();
 });
 $('#subproductos2').on('click',function(){
    $('#subnivel2').toggle('slow');
    $('#subnivel1').hide();
    $('#subnivel3').hide();
    $('#subnivel4').hide();
    $('#subnivel5').hide();
    $('#subnivel6').hide();
 });
 $('#subproductos3').on('click',function(){
    $('#subnivel3').toggle('slow');
    $('#subnivel2').hide();
    $('#subnivel1').hide();
    $('#subnivel4').hide();
    $('#subnivel5').hide();
    $('#subnivel6').hide();
 });
 $('#subproductos4').on('click',function(){
    $('#subnivel4').toggle('slow');
    $('#subnivel2').hide();
    $('#subnivel3').hide();
    $('#subnivel1').hide();
    $('#subnivel5').hide();
    $('#subnivel6').hide();
 });
 $('#subproductos5').on('click',function(){
    $('#subnivel5').toggle('slow');
    $('#subnivel2').hide();
    $('#subnivel3').hide();
    $('#subnivel4').hide();
    $('#subnivel1').hide();
    $('#subnivel6').hide();
 });
 $('#subproductos6').on('click',function(){
    $('#subnivel6').toggle('slow');
    $('#subnivel2').hide();
    $('#subnivel3').hide();
    $('#subnivel4').hide();
    $('#subnivel5').hide();
    $('#subnivel1').hide();
 });
});
